function [w, countCoRated]=eqSimMedianRobustR(actveUsr, neighbor, item, statsRow, loopParams)
ratingsCommon = setdiff(intersect(find(actveUsr), find(neighbor)), item);
countCoRated = length(ratingsCommon);

medAc = median(actveUsr(setdiff(find(actveUsr),item)));
medNg = median(neighbor(find(neighbor)));

w = (...
    (actveUsr(ratingsCommon)-medAc) * ...
    (neighbor(ratingsCommon)-medNg)' ...
    ) / ( ...
    sqrt(sum((actveUsr(ratingsCommon)-medAc) .^2)) *...
    sqrt(sum((neighbor(ratingsCommon)-medNg) .^2)) ...
    );
end %end of function