function printStatsProgress(path, str, elapsedTime, a, cntR, i, item, cntC, eq, cntEq)

percentage    = (100 * (cntC*cntEq*(a-1) + cntEq*(i-1) + eq)) / (cntR * cntC * cntEq);
remainingTime = elapsedTime*(100-percentage)/percentage;

text = path;
text = [text newline str];
text = [text newline '                          ' , num2str(cntR), '×', num2str(cntC), '×', num2str(cntEq)];
text = [text newline '                          ' , num2str(a, ['%0',num2str(numel(num2str(cntR))),'i']), ...
                                               ':', num2str(i, ['%0',num2str(numel(num2str(cntC))),'i']), ...
                                               '(', num2str(item), ')'];
text = [text newline '                          %', num2str(round(percentage,3))];
text = [text newline '            Elapsed time: ', ...
    num2str((   round(elapsedTime/3600 - 0.5)),      '%02i'), 'h ', ...
    num2str(mod(round(elapsedTime/60   - 0.5) , 60), '%02i'), 'm ', ...
    num2str(mod(round(elapsedTime),60),              '%02i'), 's ', ...
    '(', datestr(now-(elapsedTime/86400),'dd-mmm-yyyy HH:MM'), ')'];
if(0~=remainingTime)
    text = [text newline 'Estimated remaining time: ', ...
        num2str((   round(remainingTime/3600 - 0.5)),      '%02i'), 'h ', ...
        num2str(mod(round(remainingTime/60   - 0.5) , 60), '%02i'), 'm ', ...
        num2str(mod(round(remainingTime),60),              '%02i'), 's ', ...
        '(', datestr(now+(remainingTime/86400),'dd-mmm-yyyy HH:MM'), ')'];
end
clc;
disp(text);

end %end of function
